server:
  application:
    name: productServer
  port: 8081
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:productServer}
      properties:
        spring:
                  json:
                    use:
                      type:
                        headers: false
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
kafka:
  topic:
    product:
      request: product-req-topic
      reply: product-req-reply-topic
  request-reply:
    timeout-ms: 10000
product:
  topic:
    request:
      numPartitions: 5